name: Lint Moonstream db

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "db/**"
      - "!db/deploy/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools
      - name: Install test requirements
        working-directory: ./db
        run: pip install -e .[dev]
      - name: Mypy type check
        working-directory: ./db
        run: mypy moonstreamdb/
      - name: Black syntax check
        working-directory: ./db
        run: black --check moonstreamdb/
